std_msgs/Header header	# use frame_id to identify the sensor which detected the obstacle
float32 dx		# X component of direction to obstacle in sensor's frame of reference
float32 dy		# Y component of direction to obstacle in sensor's frame of reference
float32 dz		# Z component of direction to obstacle in sensor's frame of reference
float32 range		# distance to the obstacle as measured by the sensor
