#!/bin/sh
### BEGIN INIT INFO
# Provides:          drivebase
# Required-Start:    hostname $local_fs $network roscore
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: drivebase
# Description:       Start drivebase_starter.sh
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:
. /lib/init/vars.sh

do_start () {
	sudo -u pi /home/pi/catkin_ws/src/drivebase/drivebase_starter.sh&
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  *)
	echo "Usage: roomba_teleop [start|stop]" >&2
	exit 3
	;;
esac

:
